# -- Replicas.
# Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas
replicaCount: 1

# Image.
# Ref: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- Image repository.
  repository: public.ecr.aws/l8m2k1n1/netapp/wave-operator
  # -- Image pull policy.
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is latest.
  tag:

# -- Image pull secrets.
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# Service account.
# Ref:
serviceAccount:
  # -- Controls whether a service account should be created.
  create: true
  # -- Service account annotations.
  annotations: {}
  # -- Service account name.
  name: wave-operator

# -- Pod annotations.
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext: {}
  # fsGroup: 2000

# -- Container security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Resource requests and limits.
# Ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

# -- Node selector.
nodeSelector: {}

# -- Tolerations for nodes that have taints on them.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Pod scheduling preferences.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  # -- Node affinity.
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
