apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ocean-controller.clusterRoleBindingName" . }}
  labels:
  {{- include "ocean-controller.commonLabels" . | nindent 4 }}
  {{- include "ocean-controller.controllerLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ocean-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ocean-controller.name" . }}
  namespace: {{ include "ocean-controller.namespace" . }}
