{{- if ne (include "ocean-controller.namespace" .) "kube-system" }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "ocean-controller.priorityClassName" . }}
  namespace: {{ include "ocean-controller.namespace" . }}
  labels:
  {{- include "ocean-controller.commonLabels" . | nindent 4 }}
  {{- include "ocean-controller.controllerLabels" . | nindent 4 }}
value: 1000000000
description: "Used for critical pods that must run in the cluster, but can be moved to another node if necessary. Priority classes `system-cluster-critical` and `system-node-critical` are limited to `kube-system` namespace. See: https://github.com/kubernetes/kubernetes/issues/60596."
{{- end }}
