{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-controller.secretName" . }}
  namespace: {{ include "ocean-controller.namespace" . }}
  labels:
  {{- include "ocean-controller.commonLabels" . | nindent 4 }}
  {{- include "ocean-controller.controllerLabels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "spotinst.token is missing" .Values.spotinst.token | b64enc }}
  account: {{ required "spotinst.account is missing" .Values.spotinst.account | b64enc }}
{{- end -}}
