apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ocean-controller.serviceAccountName" . }}
  namespace: {{ include "ocean-controller.namespace" . }}
  labels:
  {{- include "ocean-controller.commonLabels" . | nindent 4 }}
  {{- include "ocean-controller.controllerLabels" . | nindent 4 }}
