apiVersion: v2
name: ocean-controller
description: A Helm chart for Ocean Controller
type: application
version: 1.0.92
appVersion: 1.0.77
home: https://github.com/spotinst/charts/tree/main/charts/ocean-controller
icon: https://docs.spot.io/_media/images/spot_mark.png
sources:
- https://github.com/spotinst/ocean-controller
keywords:
- spot
- ocean
- controller
maintainers:
- name: yeminiori
  email: ori.yemini@netapp.com
- name: fromor
  email: or.from@netapp.com
