apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocean-operator.fullname" . }}
  labels:
    {{- include "ocean-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.spotinst }}
  clusterIdentifier: {{ required "spotinst.clusterIdentifier is missing" .clusterIdentifier }}
  {{- if .acdIdentifier }}
  acdIdentifier: {{ .acdIdentifier }}
  {{- end }}
  {{- end }}
