dependencies:
- name: provisioner
  version: 0.1.*
  condition: provisioner.enabled
- name: ocean-toolkit
  version: 0.1.*
  repository: https://charts.helm.sh/stable
  condition: ocean-toolkit.enabled
- name: efs-provisioner
  version: 0.13.*
  repository: https://charts.helm.sh/stable
  condition: efs-provisioner.enabled
- name: spark-history-server
  version: 1.3.*
  repository: https://charts.helm.sh/stable
  condition: spark-history-server.enabled
- name: sparkoperator
  version: 0.8.*
  repository: https://charts.helm.sh/incubator
  condition: sparkoperator.enabled
